In [1]:
### Series

import pandas as pd

In [3]:
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
### Create a series from dictionary elements

data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [5]:
data = [10,20,30]

index=['a','b','c']

pd.Series(data,index)

a    10
b    20
c    30
dtype: int64

In [6]:
### Data Frame

data = {
    'Name':['Krish', 'John', 'Jack'],
    'Age': [20,30,45],
    'City': ['Banglore', 'New york', 'Florida']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Krish   20  Banglore
1   John   30  New york
2   Jack   45   Florida
<class 'pandas.core.frame.DataFrame'>

In [7]:
import numpy as np
np.array(df)

array([['Krish', 20, 'Banglore'],
       ['John', 30, 'New york'],
       ['Jack', 45, 'Florida']], dtype=object)

In [12]:
### Create a df from a list of dict

data=[
    {
        'Name':'Krish','Age':32,'City':'Banglore'
    },{
        'Name':'John','Age':34,'City':'Banglore'
    },
    {
        'Name':'Jack','Age':40,'City':'Banglore'
    }
]

df=pd.DataFrame(data)
print(df)

    Name  Age      City
0  Krish   32  Banglore
1   John   34  Banglore
2   Jack   40  Banglore

In [9]:
np.array(df)

array([['Krish', 32, 'Banglore'],
       ['John', 34, 'Banglore'],
       ['Jack', 40, 'Banglore']], dtype=object)

In [10]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [11]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [13]:
### Accessing data from dataframe
df['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: object

In [14]:
df.loc[0]

Name       Krish
Age           32
City    Banglore
Name: 0, dtype: object

In [15]:
df.iloc[0]

Name       Krish
Age           32
City    Banglore
Name: 0, dtype: object

In [16]:
df.loc[0][0]

/var/folders/8_/828vbj5d2rs_89mwjs3rtmr40000gn/T/ipykernel_25018/2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Krish'

In [18]:
df.iloc[0][2]

/var/folders/8_/828vbj5d2rs_89mwjs3rtmr40000gn/T/ipykernel_25018/2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Banglore'

In [20]:
### Accessing a specified element

df

    Name  Age      City
0  Krish   32  Banglore
1   John   34  Banglore
2   Jack   40  Banglore

In [22]:
age=df.at[1,'Age']
print(age)

34

In [24]:
df.iat[2,2]

'Banglore'

In [25]:
### Data manipulation with data frames

df

    Name  Age      City
0  Krish   32  Banglore
1   John   34  Banglore
2   Jack   40  Banglore

In [26]:
df['Salary'] = [50000,60000,70000]
df

    Name  Age      City  Salary
0  Krish   32  Banglore   50000
1   John   34  Banglore   60000
2   Jack   40  Banglore   70000

In [28]:
### Remove a cloumn

df.drop('Salary',axis=1,inplace=True)
df

    Name  Age      City
0  Krish   32  Banglore
1   John   34  Banglore
2   Jack   40  Banglore

In [ ]:
### Add age to the column

df['Age']=df['Age']+1
df

    Name  Age      City
0  Krish   33  Banglore
1   John   35  Banglore
2   Jack   41  Banglore

In [30]:
df.drop(0)

   Name  Age      City
1  John   35  Banglore
2  Jack   41  Banglore

In [31]:
df

    Name  Age      City
0  Krish   33  Banglore
1   John   35  Banglore
2   Jack   41  Banglore

In [32]:
df.drop(0,inplace=True)

In [33]:
df

   Name  Age      City
1  John   35  Banglore
2  Jack   41  Banglore

In [34]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [35]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000